project:
  type: website
  output-dir: docs

website:
  title: "Adam Aiken @ Elon Finance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

